name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm --workspace packages/server test --if-present
      - run: npm --workspace packages/web test --if-present

      - run: npm install --prefix packages/server
      - run: npm install --prefix packages/web
      - run: npm test --prefix packages/server
      - run: npm test --prefix packages/web

