name: Seed DB

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm --workspace packages/server run seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
